-- phpMyAdmin SQL Dump
-- version 4.5.2
-- http://www.phpmyadmin.net
--
-- Värd: localhost
-- Tid vid skapande: 05 jan 2017 kl 23:02
-- Serverversion: 10.1.16-MariaDB
-- PHP-version: 7.0.9

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Databas: `db_blogg`
--


-- --------------------------------------------------------

--
-- Tabellstruktur `categories`
--

CREATE TABLE `categories` (
  `cat_id` int(255) NOT NULL,
  `cat_name` varchar(255) COLLATE utf8_swedish_ci NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_swedish_ci;

--
-- Dumpning av Data i tabell `categories`
--

INSERT INTO `categories` (`cat_id`, `cat_name`) VALUES
(1, 'R&B'),
(2, 'Rock'),
(3, 'Pop'),
(4, 'Polka');

-- --------------------------------------------------------

--
-- Tabellstruktur `comments`
--

CREATE TABLE `comments` (
  `com_id` int(255) NOT NULL,
  `name` varchar(255) COLLATE utf8_swedish_ci NOT NULL,
  `email` varchar(255) COLLATE utf8_swedish_ci NOT NULL,
  `create_time` datetime(6) NOT NULL,
  `text` text COLLATE utf8_swedish_ci NOT NULL,
  `fk_post_id` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_swedish_ci;

--
-- Dumpning av Data i tabell `comments`
--

INSERT INTO `comments` (`com_id`, `name`, `email`, `create_time`, `text`, `fk_post_id`) VALUES
(1, 'Henrik', 'hans@hans.se', '2016-12-08 13:53:14.000000', 'DÃ¥lig blogg', 97),
(3, 'Din rÃ¥tta', 'du@du.com', '2016-12-11 14:49:52.000000', 'Du Ã¤r en liten plutt.', 105),
(4, 'Olav', 'olav.skotkonung@gmail.com', '2016-12-11 20:15:57.000000', 'HÃ¤r vare kÃ¶nstiga inlÃ¤gg.', 110),
(5, 'Erik', 'erik.rode@svalbard.com', '2016-12-11 20:41:05.000000', 'Tveksamt... Mycket tveksamt.', 110),
(6, 'rode', 'erik@rode.com', '2016-12-11 20:42:22.000000', 'Nja, det tror jag inte.', 110),
(7, 'assar', 'assa@hassar.gmail.com', '2016-12-11 21:11:42.000000', 'Nja, det vet jag inget om.', 110),
(8, 'assar', 'assa@hassar.gmail.com', '2016-12-11 21:13:28.000000', 'Nja, det vet jag inget om.', 110),
(9, 'assar', 'assa@hassar.gmail.com', '2016-12-11 21:14:53.000000', 'Nja, det vet jag inget om.', 110);

-- --------------------------------------------------------

--
-- Tabellstruktur `posts`
--

CREATE TABLE `posts` (
  `post_id` int(255) NOT NULL,
  `create_time` datetime(6) NOT NULL,
  `edit_time` datetime(6) NOT NULL,
  `title` varchar(255) COLLATE utf8_swedish_ci NOT NULL,
  `text` text COLLATE utf8_swedish_ci NOT NULL,
  `is_published` tinyint(1) NOT NULL,
  `user_id` int(255) NOT NULL,
  `cat_id` int(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_swedish_ci;

--
-- Dumpning av Data i tabell `posts`
--

INSERT INTO `posts` (`post_id`, `create_time`, `edit_time`, `title`, `text`, `is_published`, `user_id`, `cat_id`) VALUES
(96, '2016-12-07 20:42:28.000000', '0000-00-00 00:00:00.000000', 'Harry bloggar', '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Equidem, sed audistine modo de Carneade? Ita prorsus, inquam; Duo Reges: constructio interrete. Hoc Hieronymus summum bonum esse dixit. Quonam, inquit, modo? Quid est, quod ab ea absolvi et perfici debeat? Quid me istud rogas? Quid de Platone aut de Democrito loquar? </p>\r\n\r\n<dl>\r\n	<dt><dfn>Quid Zeno?</dfn></dt>\r\n	<dd>Itaque rursus eadem ratione, qua sum paulo ante usus, haerebitis.</dd>\r\n	<dt><dfn>Quibusnam praeteritis?</dfn></dt>\r\n	<dd>Quid censes in Latino fore?</dd>\r\n	<dt><dfn>Magna laus.</dfn></dt>\r\n	<dd>Res enim se praeclare habebat, et quidem in utraque parte.</dd>\r\n	<dt><dfn>Easdemne res?</dfn></dt>\r\n	<dd>Itaque in rebus minime obscuris non multus est apud eos disserendi labor.</dd>\r\n</dl>\r\n\r\n\r\n<p>Ne in odium veniam, si amicum destitero tueri. Ut in geometria, prima si dederis, danda sunt omnia. </p>\r\n\r\n<p>Quantum Aristoxeni ingenium consumptum videmus in musicis? Sit hoc ultimum bonorum, quod nunc a me defenditur; Haec bene dicuntur, nec ego repugno, sed inter sese ipsa pugnant. Hic Speusippus, hic Xenocrates, hic eius auditor Polemo, cuius illa ipsa sessio fuit, quam videmus. </p>\r\n\r\n<p>Videamus animi partes, quarum est conspectus illustrior; Prodest, inquit, mihi eo esse animo. Nunc ita separantur, ut disiuncta sint, quo nihil potest esse perversius. Age nunc isti doceant, vel tu potius quis enim ista melius? Beatus sibi videtur esse moriens. At iste non dolendi status non vocatur voluptas. Aliter homines, aliter philosophos loqui putas oportere? </p>\r\n\r\n<ol>\r\n	<li>Nec enim, omnes avaritias si aeque avaritias esse dixerimus, sequetur ut etiam aequas esse dicamus.</li>\r\n	<li>Animum autem reliquis rebus ita perfecit, ut corpus;</li>\r\n</ol>\r\n\r\n\r\n<p>Quamquam ab iis philosophiam et omnes ingenuas disciplinas habemus; Quae est igitur causa istarum angustiarum? Sit sane ista voluptas. Urgent tamen et nihil remittunt. An nisi populari fama? Ab his oratores, ab his imperatores ac rerum publicarum principes extiterunt. </p>\r\n\r\n', 1, 5, 2),
(97, '2016-12-07 20:43:41.000000', '0000-00-00 00:00:00.000000', 'Mitt fÃ¶rsta inlÃ¤gg', '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Si mala non sunt, iacet omnis ratio Peripateticorum. Quid de Platone aut de Democrito loquar? Cur fortior sit, si illud, quod tute concedis, asperum et vix ferendum putabit? </p>\r\n\r\n<ol>\r\n	<li>Audeo dicere, inquit.</li>\r\n	<li>Non potes ergo ista tueri, Torquate, mihi crede, si te ipse et tuas cogitationes et studia perspexeris;</li>\r\n	<li>Nosti, credo, illud: Nemo pius est, qui pietatem-;</li>\r\n	<li>Aliis esse maiora, illud dubium, ad id, quod summum bonum dicitis, ecquaenam possit fieri accessio.</li>\r\n	<li>Commoda autem et incommoda in eo genere sunt, quae praeposita et reiecta diximus;</li>\r\n	<li>Quamquam non negatis nos intellegere quid sit voluptas, sed quid ille dicat.</li>\r\n</ol>\r\n\r\n\r\n<p>Quae cum magnifice primo dici viderentur, considerata minus probabantur. Immo alio genere; Inde sermone vario sex illa a Dipylo stadia confecimus. Quid enim tanto opus est instrumento in optimis artibus comparandis? </p>\r\n\r\n<p>Mene ergo et Triarium dignos existimas, apud quos turpiter loquare? Eam tum adesse, cum dolor omnis absit; Non quam nostram quidem, inquit Pomponius iocans; Vide igitur ne non debeas verbis nostris uti, sententiis tuis. </p>\r\n\r\n<p>Duo Reges: constructio interrete. Hoc sic expositum dissimile est superiori. Tecum optime, deinde etiam cum mediocri amico. Nihil enim iam habes, quod ad corpus referas; Idem iste, inquam, de voluptate quid sentit? Atqui perspicuum est hominem e corpore animoque constare, cum primae sint animi partes, secundae corporis. Quae cum dixisset, finem ille. Et quidem, Cato, hanc totam copiam iam Lucullo nostro notam esse oportebit; A villa enim, credo, et: Si ibi te esse scissem, ad te ipse venissem. Ergo instituto veterum, quo etiam Stoici utuntur, hinc capiamus exordium. </p>\r\n\r\n<p>Quid ad utilitatem tantae pecuniae? Iam in altera philosophiae parte. Animi enim quoque dolores percipiet omnibus partibus maiores quam corporis. Quodsi ipsam honestatem undique pertectam atque absolutam. Apparet statim, quae sint officia, quae actiones. Quantum Aristoxeni ingenium consumptum videmus in musicis? Suo enim quisque studio maxime ducitur. </p>\r\n\r\n<dl>\r\n	<dt><dfn>Nihil sane.</dfn></dt>\r\n	<dd>Vitae autem degendae ratio maxime quidem illis placuit quieta.</dd>\r\n	<dt><dfn>Moriatur, inquit.</dfn></dt>\r\n	<dd>Sed id ne cogitari quidem potest quale sit, ut non repugnet ipsum sibi.</dd>\r\n	<dt><dfn>Numquam facies.</dfn></dt>\r\n	<dd>Videamus animi partes, quarum est conspectus illustrior;</dd>\r\n	<dt><dfn>Numquam facies.</dfn></dt>\r\n	<dd>Quae tamen a te agetur non melior, quam illae sunt, quas interdum optines.</dd>\r\n	<dt><dfn>Avaritiamne minuis?</dfn></dt>\r\n	<dd>Non minor, inquit, voluptas percipitur ex vilissimis rebus quam ex pretiosissimis.</dd>\r\n</dl>\r\n\r\n\r\n', 1, 6, 4),
(98, '2016-12-08 11:57:39.000000', '0000-00-00 00:00:00.000000', 'Utkast 1', '\r\n<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus ac magna non augue porttitor scelerisque ac id diam. Mauris elit velit, lobortis sed interdum at, vestibulum vitae libero. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque iaculis ligula ut ipsum mattis viverra. Nulla a libero metus. Integer gravida tempor metus eget condimentum. Integer eget iaculis tortor. Nunc sed ligula sed augue rutrum ultrices eget nec odio. Morbi rhoncus, sem laoreet tempus pulvinar, leo diam varius nisi, sed accumsan ligula urna sed felis. Mauris molestie augue sed nunc adipiscing et pharetra ligula suscipit. In euismod lectus ac sapien fringilla ut eleifend lacus venenatis.  </p>\r\n\r\n<p>Proin suscipit luctus orci placerat fringilla. Donec hendrerit laoreet risus eget adipiscing. Suspendisse in urna ligula, a volutpat mauris. Sed enim mi, bibendum eu pulvinar vel, sodales vitae dui. Pellentesque sed sapien lorem, at lacinia urna. In hac habitasse platea dictumst. Vivamus vel justo in leo laoreet ullamcorper non vitae lorem. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin bibendum ullamcorper rutrum.  </p>\r\n\r\n<p>In facilisis scelerisque dui vel dignissim. Sed nunc orci, ultricies congue vehicula quis, facilisis a orci. In aliquet facilisis condimentum. Donec at orci orci, a dictum justo. Sed a nunc non lectus fringilla suscipit. Vivamus pretium sapien sit amet mauris aliquet eleifend vel vitae arcu. Fusce pharetra dignissim nisl egestas pretium.  </p>\r\n\r\n<p>Nullam eros mi, mollis in sollicitudin non, tincidunt sed enim. Sed et felis metus, rhoncus ornare nibh. Ut at magna leo. Suspendisse egestas est ac dolor imperdiet pretium. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam porttitor, erat sit amet venenatis luctus, augue libero ultrices quam, ut congue nisi risus eu purus. Cras semper consectetur elementum. Nulla vel aliquet libero. Vestibulum eget felis nec purus commodo convallis. Aliquam erat volutpat.  </p>\r\n\r\n<p>Proin ornare ligula eu tellus tempus elementum. Aenean bibendum iaculis mi, nec blandit lacus interdum vitae. Vestibulum non nibh risus, a scelerisque purus. Ut vel arcu ac tortor adipiscing hendrerit vel sed massa. Fusce sem libero, lacinia vulputate interdum non, porttitor non quam. Aliquam sed felis ligula. Duis non nulla magna.  </p>', 0, 3, 2),
(99, '2016-12-08 12:20:54.000000', '0000-00-00 00:00:00.000000', 'Utkast 2', 'En vacker sommardag.', 0, 3, 1),
(100, '2016-12-08 12:21:04.000000', '0000-00-00 00:00:00.000000', 'Roliga timmen', 'eller?', 0, 3, 4),
(101, '2016-12-08 12:21:14.000000', '0000-00-00 00:00:00.000000', 'KrÃ¤ftor Ã¤r gott', 'Eller hur!', 0, 3, 3),
(104, '0000-00-00 00:00:00.000000', '0000-00-00 00:00:00.000000', 'Hej bloggen', 'Ni är allt ena trevliga laxar. Lorem Ipsum är en utfyllnadstext från tryck- och förlagsindustrin. Lorem ipsum har varit standard ända sedan 1500-talet, när en okänd boksättare tog att antal bokstäver och blandade dem för att göra ett provexemplar av en bok. Lorem ipsum har inte bara överlevt fem århundraden, utan även övergången till elektronisk typografi utan större förändringar. Det blev allmänt känt på 1960-talet i samband med lanseringen av Letraset-ark med avsnitt av Lorem Ipsum, och senare med mjukvaror som Aldus PageMaker.', 1, 6, 1),
(105, '2016-12-11 14:07:23.000000', '0000-00-00 00:00:00.000000', 'Hey everyone', 'But I must explain to you how all this mistaken idea of denouncing pleasure and praising pain was born and I will give you a complete account of the system, and expound the actual teachings of the great explorer of the truth, the master-builder of human happiness. No one rejects, dislikes, or avoids pleasure itself, because it is pleasure, but because those who do not know how to pursue pleasure rationally encounter consequences that are extremely painful. Nor again is there anyone who loves or pursues or desires to obtain pain of itself, because it is pain, but because occasionally circumstances occur in which toil and pain can procure him some great pleasure. To take a trivial example, which of us ever undertakes laborious physical exercise, except to obtain some advantage from it? But who has any right to find fault with a man who chooses to enjoy a pleasure that has no annoying consequences, or one who avoids a pain that produces no resultant pleasure?', 1, 7, 3),
(106, '2016-12-11 20:10:37.000000', '0000-00-00 00:00:00.000000', 'OtÃ¤ck skada', 'Mchitarjan har nu varit direkt involverad i fyra mÃ¥l pÃ¥ lika mÃ¥nga matcher.\r\nMen i slutet av matchen utspelades scener som lÃ¤r skrÃ¤mma Manchester United ordentligt. MatchhjÃ¤lten blev trampad i bakhasorna av Danny Rose och fastnade med fotleden i grÃ¤set.\r\nHan fÃ¶ll ihop med stora smÃ¤rtor och tvingades till slut ledas av planen med bÃ¥r.\r\nâ€“ Jag sÃ¥g honom inte i omklÃ¤dningsrummet direkt efter matchen men jag hoppas att han Ã¤r okej, sÃ¤ger Zlatan Ibrahimovic.\r\nOch de fÃ¶rsta prognoserna tyder pÃ¥ att Mchitarjan snart Ã¤r tillbaka.\r\nâ€“ Det var inte sÃ¥ farligt som det sÃ¥g ut. Jag skulle tro att han blir borta i en vecka, sÃ¤ger trÃ¤naren JosÃ© Mourinho.\r\nMatchen slutade alltsÃ¥ 1-0 till United.\r\nâ€“ En skÃ¶n seger. Vi har spelat bra pÃ¥ senare tid men inte riktigt fÃ¥tt med oss resultaten. Kan vi fortsÃ¤tta spela sÃ¥ hÃ¤r sÃ¥ kommer vi att gÃ¥ lÃ¥ngt, sÃ¤ger Ibrahimovic.', 1, 7, 1),
(107, '2016-12-11 20:11:46.000000', '0000-00-00 00:00:00.000000', 'Inga poliser pÃ¥ vÃ¤garna', 'Andelen svenska Ã¥kerier som har trafik pÃ¥ kontinenten har fallit till nÃ¤ra noll de senaste 20 Ã¥ren. Enligt Ulric LÃ¥ngberg, branschchef pÃ¥ Sveriges Ã…kerifÃ¶retag, stod den kontinentala trafiken fÃ¶r 7-8 procent av den svenska Ã¥kerinÃ¤ringen nÃ¤r Sverige gick med i EU. I dag ligger det runt 1 procent.\r\n\r\nLÃ¥ngberg pÃ¥pekar att det i grunden Ã¤r bra med livlig lastbilstrafik mellan Sverige och Europa; det betyder att vÃ¥r export och import fungerar.\r\n\r\nâ€“ Det Ã¤r alltsÃ¥ inget konstigt att det finns internationell trafik pÃ¥ vÃ¥ra vÃ¤gar.\r\n\r\nLÃ„S Ã„VEN\r\n\r\n\r\nâ€Ã…kerier som Postnord drivs som kriminella MC-gÃ¤ngâ€\r\nSVD GRANSKAR Ã…KERINÃ„RINGEN  Idag 08.43\r\nMen sedan EU-intrÃ¤det har flÃ¶dena fÃ¶rÃ¤ndrats. FrÃ¥n att trafiken tidigare utgick frÃ¥n Sverige med exportvaror och Ã¥tervÃ¤nde med import, Ã¤r det i stÃ¤llet bilar som fÃ¶rst kommer med importvaror till Sverige och Ã¥tervÃ¤nder till kontinenten med exportvaror.\r\n\r\nâ€“ Men eftersom vi importerar mer Ã¤n vi exporterar kommer det mÃ¥nga bilar som inte fÃ¥r nÃ¥got med sig ut. De ser att den svenska marknaden Ã¤r bra, med lÃ¶ner och transportpriser man inte kommer i nÃ¤rheten av i stora delar Europa. Vi klarar inte av den konkurrensen om det dessutom tummas pÃ¥ lagar och regler, sÃ¤ger LÃ¥ngberg.', 1, 7, 4),
(108, '2016-12-11 20:12:27.000000', '0000-00-00 00:00:00.000000', 'The Battle of Adwa', 'The Italians suffered about 7,000 killed and 1,500 wounded in the battle and subsequent retreat back into Eritrea, with 3,000 taken prisoner. Brigadiers Dabormida and Arimondi were amongst the dead. Ethiopian losses have been estimated at around 4,000â€“5,000 killed and 8,000 wounded.[31][36] In their flight to Eritrea, the Italians left behind all of their artillery and 11,000 rifles, as well as most of their transport.[36] As Paul B. Henze notes, "Baratieri''s army had been completely annihilated while Menelik''s was intact as a fighting force and gained thousands of rifles and a great deal of equipment from the fleeing Italians."[37] The 3,000 Italian prisoners, who included Brigadier Albertone, appear to have been treated as well as could be expected under difficult circumstances, though about 200 died of their wounds in captivity.[38] However, 800 captured askaris, regarded as traitors by the Ethiopians, had their right hands and left feet amputated. Augustus Wylde records when he visited the battlefield months after the battle, the pile of severed hands and feet was still visible, "a rotting heap of ghastly remnants."[39] Further, many had not survived their punishment, Wylde writing how the neighborhood of Adwa "was full of their freshly dead bodies; they had generally crawled to the banks of the streams to quench their thirst, where many of them lingered unattended and exposed to the elements until death put an end to their sufferings."[40] There does not appear to be any foundation for reports that some Italians were castrated and these may reflect confusion with the atrocious treatment of the askari prisoners.[41]', 1, 7, 4),
(109, '2016-12-11 20:13:26.000000', '0000-00-00 00:00:00.000000', 'Ã…kerier drivs av kriminella gÃ¤ng', 'Tommy Jonsson och hans medarbetare har i projektet â€Ordning och reda inom Ã¥keribranschenâ€ kartlagt de mer ljusskygga delarna av branschen. Det handlar om hur stora och vÃ¤lkÃ¤nda fÃ¶retag, dÃ¤ribland statliga Postnord, utfÃ¶r transporter via svenska eller utlÃ¤ndska Ã¥kerier och bemanningsfÃ¶retag.\r\n\r\nMellan bestÃ¤llaren och utfÃ¶raren finns ofta mÃ¥nga led dÃ¤r den chauffÃ¶r som fÃ¥r uppdraget att kÃ¶ra lastbilen ofta Ã¤r bosatt i Bulgarien, RumÃ¤nien eller Makedonien. ErsÃ¤ttningen de fÃ¥r ligger mycket lÃ¥ngt under de lÃ¶ner som gÃ¤ller i Nord- och VÃ¤steuropa.\r\n\r\nEnligt Tommy Jonsson kostar en svensk chauffÃ¶r runt 40 euro per timme, inklusive skatter och sociala avgifter. Motsvarande kostnad fÃ¶r rumÃ¤nska, bulgariska eller litauiska chauffÃ¶rer ligger mellan 3 och 6 euro.\r\n\r\nâ€“ En del av de hÃ¤r transporterna gÃ¥r dessutom inte att finansiera utan att blanda in organiserad kriminalitet. Det kan handla om att smuggla sprit eller till och med vapen, vissa har med sig stÃ¶ldgods fÃ¶r att fÃ¥ det att gÃ¥ ihop, sÃ¤ger Tommy Jonsson.\r\n\r\n Tidigare sÃ¥g vi mÃ¥nga chauffÃ¶rer frÃ¥n Polen, sedan var det frÃ¥n Bulgarien och RumÃ¤nien. Nu kan det vara makedonska fÃ¶rare som kÃ¶r pÃ¥ falska bulgariska kÃ¶rkort fÃ¶r bulgariska Ã¥kerier.\r\nHan berÃ¤ttar om lastbilar med registreringsskyltar som sitter fast med bultband eller har falska registreringsskyltar. Det florerar Ã¤ven mÃ¥nga falska handlingar och olika nÃ¶dvÃ¤ndiga tillstÃ¥nd kan exempelvis kÃ¶pas billigt i Ã–steuropa, enligt Tommy Jonsson.', 1, 7, 2),
(110, '2016-12-11 20:14:20.000000', '0000-00-00 00:00:00.000000', 'IS i offensiv mot Palmyra', 'De senaste dagarna har vÃ¤rldsarvsstaden Palmyra i centrala Syrien Ã¥terigen blivit fÃ¶remÃ¥l fÃ¶r strider. IS hÃ¶ll platsen mellan maj 2015 och mars i Ã¥r, och vÃ¤ckte vÃ¤rldens ilska efter att ha fÃ¶rstÃ¶rt flera helgedomar.\r\n\r\nPÃ¥ torsdagen inledde terrorgruppen ovÃ¤ntat en ny offensiv mot Palmyra, vilket ledde till att IS pÃ¥ sÃ¶ndagen Ã¥tererÃ¶vrade staden. Per JÃ¶nsson, MellanÃ¶sternexpert vid Utrikespolitiska institutet, tror dock inte att IS har nÃ¥gra planer pÃ¥ att hÃ¥lla Palmyra under en lÃ¤ngre tid.', 1, 7, 4),
(111, '2016-12-17 00:05:25.000000', '0000-00-00 00:00:00.000000', 'Hola hoppsan', 'PÃ¥ presskonferensen uppger Obama ocksÃ¥ att han vid ett mÃ¶te pratat om hackerattacken direkt med Rysslands Vladimir Putin i september.\r\nâ€“ Jag sa att de mÃ¥ste sluta, annars fÃ¥r det allvarliga konsekvenser, sÃ¤ger Obama.\r\nHan sÃ¤ger ocksÃ¥ att de dÃ¤refter inte sett nÃ¥gra fler attacker mot valprocessen, enligt ABC News.\r\nHan var ocksÃ¥ tydlig med att de Ã¤r pÃ¥ det klara med att allt pekar pÃ¥ att Ryssland lÃ¥g bakom hackerattacken.\r\nâ€“ Eniga underrÃ¤ttelseuppgifter pekar pÃ¥ att Ryssland lÃ¥g bakom hackerattacken, sÃ¤ger han.\r\nPresidenten fick ocksÃ¥ frÃ¥gan om han tror att Vladimir Putin haft kÃ¤nnedom om attackerna, nÃ¥got han inte ville ge ett rakt svar pÃ¥ utan nÃ¶jde sig med att sÃ¤ga att Ryssland Ã¤r starkt hierarkiskt styrt:\r\nâ€“ Inte mycket hÃ¤nder i Ryssland utan Vladimir Putin.\r\nUnder fredagen rapporteras samtidigt att FBI och CIA nu Ã¤r Ã¶verens om att Ryssland lÃ¥g bakom attackerna i syfte att stÃ¶dja den numera blivande presidenten Donald Trump, enligt ett mejl frÃ¥n CIA-chefen John Brennan, uppger AP.				', 1, 7, 4),
(112, '2016-12-17 00:05:52.000000', '0000-00-00 00:00:00.000000', 'Jobbigt vÃ¤rre', 'PÃ¥ presskonferensen uppger Obama ocksÃ¥ att han vid ett mÃ¶te pratat om hackerattacken direkt med Rysslands Vladimir Putin i september.\r\nâ€“ Jag sa att de mÃ¥ste sluta, annars fÃ¥r det allvarliga konsekvenser, sÃ¤ger Obama.\r\nHan sÃ¤ger ocksÃ¥ att de dÃ¤refter inte sett nÃ¥gra fler attacker mot valprocessen, enligt ABC News.\r\nHan var ocksÃ¥ tydlig med att de Ã¤r pÃ¥ det klara med att allt pekar pÃ¥ att Ryssland lÃ¥g bakom hackerattacken.\r\nâ€“ Eniga underrÃ¤ttelseuppgifter pekar pÃ¥ att Ryssland lÃ¥g bakom hackerattacken, sÃ¤ger han.\r\nPresidenten fick ocksÃ¥ frÃ¥gan om han tror att Vladimir Putin haft kÃ¤nnedom om attackerna, nÃ¥got han inte ville ge ett rakt svar pÃ¥ utan nÃ¶jde sig med att sÃ¤ga att Ryssland Ã¤r starkt hierarkiskt styrt:\r\nâ€“ Inte mycket hÃ¤nder i Ryssland utan Vladimir Putin.\r\nUnder fredagen rapporteras samtidigt att FBI och CIA nu Ã¤r Ã¶verens om att Ryssland lÃ¥g bakom attackerna i syfte att stÃ¶dja den numera blivande presidenten Donald Trump, enligt ett mejl frÃ¥n CIA-chefen John Brennan, uppger AP.\r\nPÃ¥ presskonferensen uppger Obama ocksÃ¥ att han vid ett mÃ¶te pratat om hackerattacken direkt med Rysslands Vladimir Putin i september.\r\nâ€“ Jag sa att de mÃ¥ste sluta, annars fÃ¥r det allvarliga konsekvenser, sÃ¤ger Obama.\r\nHan sÃ¤ger ocksÃ¥ att de dÃ¤refter inte sett nÃ¥gra fler attacker mot valprocessen, enligt ABC News.\r\nHan var ocksÃ¥ tydlig med att de Ã¤r pÃ¥ det klara med att allt pekar pÃ¥ att Ryssland lÃ¥g bakom hackerattacken.\r\nâ€“ Eniga underrÃ¤ttelseuppgifter pekar pÃ¥ att Ryssland lÃ¥g bakom hackerattacken, sÃ¤ger han.\r\nPresidenten fick ocksÃ¥ frÃ¥gan om han tror att Vladimir Putin haft kÃ¤nnedom om attackerna, nÃ¥got han inte ville ge ett rakt svar pÃ¥ utan nÃ¶jde sig med att sÃ¤ga att Ryssland Ã¤r starkt hierarkiskt styrt:\r\nâ€“ Inte mycket hÃ¤nder i Ryssland utan Vladimir Putin.\r\nUnder fredagen rapporteras samtidigt att FBI och CIA nu Ã¤r Ã¶verens om att Ryssland lÃ¥g bakom attackerna i syfte att stÃ¶dja den numera blivande presidenten Donald Trump, enligt ett mejl frÃ¥n CIA-chefen John Brennan, uppger AP.				', 1, 7, 4),
(113, '2016-12-17 00:46:29.000000', '0000-00-00 00:00:00.000000', 'Zlatan gÃ¶r mÃ¥l', 'Halvtimmen in i matchen kladdade Tottenhams Harry Kane med bollen pÃ¥ mittplan, Ander Herrera snappade upp den â€“ och serverade Mchitarjan i djupled.\r\n27-Ã¥ringen hade chansen att spela fram Ibrahimovic men gick i stÃ¤llet pÃ¥ eget avslut â€“ och dundrade bollen rakt upp i nÃ¤ttaket.\r\nâ€“ Ett fantastiskt mÃ¥l, sÃ¤ger Zlatan Ibrahimovic.\r\nSom hyllar sin lagkamrat:\r\nâ€“ Han Ã¤r en bra spelare, det var dÃ¤rfÃ¶r han kom hit. Alla kÃ¤nner till hans kvalitÃ©er. Klubben har haft tÃ¥lamod med honom men nu har han hittat sin roll och nu Ã¤r han dominant. Han visar vÃ¤rlden vad han gÃ¥r fÃ¶r, men fÃ¶r oss var det ingen Ã¶verraskning, sÃ¤ger â€Ibraâ€.				', 1, 7, 1),
(114, '2016-12-17 00:46:48.000000', '0000-00-00 00:00:00.000000', 'Sportigt vÃ¤rre', 'Halvtimmen in i matchen kladdade Tottenhams Harry Kane med bollen pÃ¥ mittplan, Ander Herrera snappade upp den â€“ och serverade Mchitarjan i djupled.\r\n27-Ã¥ringen hade chansen att spela fram Ibrahimovic men gick i stÃ¤llet pÃ¥ eget avslut â€“ och dundrade bollen rakt upp i nÃ¤ttaket.\r\nâ€“ Ett fantastiskt mÃ¥l, sÃ¤ger Zlatan Ibrahimovic.\r\nSom hyllar sin lagkamrat:\r\nâ€“ Han Ã¤r en bra spelare, det var dÃ¤rfÃ¶r han kom hit. Alla kÃ¤nner till hans kvalitÃ©er. Klubben har haft tÃ¥lamod med honom men nu har han hittat sin roll och nu Ã¤r han dominant. Han visar vÃ¤rlden vad han gÃ¥r fÃ¶r, men fÃ¶r oss var det ingen Ã¶verraskning, sÃ¤ger â€Ibraâ€.', 1, 7, 1),
(115, '2016-12-17 00:47:25.000000', '0000-00-00 00:00:00.000000', 'MÃ¥lvaktstabbe', 'Halvtimmen in i matchen kladdade Tottenhams Harry Kane med bollen pÃ¥ mittplan, Ander Herrera snappade upp den â€“ och serverade Mchitarjan i djupled.\r\n27-Ã¥ringen hade chansen att spela fram Ibrahimovic men gick i stÃ¤llet pÃ¥ eget avslut â€“ och dundrade bollen rakt upp i nÃ¤ttaket.\r\nâ€“ Ett fantastiskt mÃ¥l, sÃ¤ger Zlatan Ibrahimovic.\r\nSom hyllar sin lagkamrat:\r\nâ€“ Han Ã¤r en bra spelare, det var dÃ¤rfÃ¶r han kom hit. Alla kÃ¤nner till hans kvalitÃ©er. Klubben har haft tÃ¥lamod med honom men nu har han hittat sin roll och nu Ã¤r han dominant. Han visar vÃ¤rlden vad han gÃ¥r fÃ¶r, men fÃ¶r oss var det ingen Ã¶verraskning, sÃ¤ger â€Ibraâ€.				', 1, 7, 1),
(116, '2016-12-18 00:49:32.000000', '0000-00-00 00:00:00.000000', 'En dag i december', 'â€“ Zlatan bÃ¶rjar bevisa att han Ã¤r en vÃ¤rldsklasspelare. Han Ã¤r 35 Ã¥r gammal men kÃ¤mpar stenhÃ¥rt i 90 minuter bÃ¥de med och utan boll, sÃ¤ger Liverpool-ikonen Steven Gerrard i BT Sport.\r\nâ€Psyke av stÃ¥lâ€\r\nUnited-trÃ¤naren JosÃ© Mourinho fyller i:\r\nâ€“ Jag Ã¤r sÃ¥ nÃ¶jd med Zlatan. Han Ã¤r en spelare som egentligen inte behÃ¶ver bevisa mer Ã¤n han redan gjort (i karriÃ¤ren) men Ã¤ndÃ¥ bestÃ¤mmer han sig fÃ¶r att ta sig an England â€“ den svÃ¥raste ligan i vÃ¤rlden â€“ som ett sista steg i karriÃ¤ren, och jag tycker att han visar att han har ett psyke av stÃ¥l, sÃ¤ger Mourinho.\r\nÃ„ven brittiska medier Ã¶verÃ¶ser svensken med lovord.\r\nLokaltidningen Manchester Evening News ger â€Ibraâ€ hÃ¶gst betyg av alla spelare â€“ en Ã¥tta pÃ¥ en tiogradig skala â€“ och The Mirror gÃ¶r exakt samma bedÃ¶mning.\r\nâ€HÃ¥rd sÃ¥ in i h*****eâ€\r\nMen â€¦ bÃ¥da tvÃ¥ hade en sak att anmÃ¤rka pÃ¥.\r\nNÃ¤mligen Ibrahimovics vÃ¥rdslÃ¶sa satsning pÃ¥ Craig Dawson i den 24:e minuten, som gav gult kort men som nog mycket vÃ¤l kunde ha renderat i ett rÃ¶tt.\r\nâ€Han visade att han Ã¤r hÃ¥rt sÃ¥ in i h*****eâ€, skriver Manchester Evening News.\r\nThe Mirror gÃ¥r ett steg lÃ¤ngre och dÃ¶mer ut satsningen som direkt vÃ¥rdslÃ¶s.\r\nâ€Han gÃ¶r tvÃ¥ mÃ¥l, men tacklingen pÃ¥ Dawson Ã¤r motbjudandeâ€, skriver man.', 1, 7, 1),
(117, '2016-12-27 21:51:52.000000', '0000-00-00 00:00:00.000000', 'Zlatan gÃ¶r mÃ¥l', 'Lorem ipsum', 1, 7, 2),
(119, '2016-12-27 22:40:22.000000', '0000-00-00 00:00:00.000000', 'Hejja', 'Hejjabara', 1, 7, 4),
(120, '2016-12-27 22:44:16.000000', '0000-00-00 00:00:00.000000', 'Heojja', 'Jeoooas', 1, 7, 3),
(121, '2016-12-27 22:45:56.000000', '0000-00-00 00:00:00.000000', 'Jojjo', 'Jojjo', 1, 7, 3),
(123, '2017-01-01 15:06:45.000000', '0000-00-00 00:00:00.000000', 'Addis Abeba between the 1960s & 1980s', '''Postcards'' mostly taken in Addis Abeba between the 1960s & 1980s G.C\r\nSource describes the 1st Picture as ''two of Addis Ababa''s fairest in national dress at the Lion of Judah Monument in 1962'' G.C\r\nHappy New Year for all who celebrate it in accordance with the Gregorian Calender', 1, 3, 2),
(124, '2017-01-01 20:20:32.000000', '0000-00-00 00:00:00.000000', 'Fransmannen hyllas rejÃ¤lt', 'Det var ett vackert anfall. Arsenal och fransmannen hyllas rejÃ¤lt.\r\nâ€“ Om man adderar hela anfallet, hela upplÃ¤gget, Girouds delaktighet med hans fÃ¶rsta klack pÃ¥ egen planhalva Ã¤r vi framme vid ett av de vackraste fotbollsmÃ¥l jag nÃ¥gonsin har sett, sÃ¤ger Sportbladets Erik Niva i Viasats studio.\r\nâ€“ Jag vet att det finns en allergi mot att uttrycka sig drastiskt dÃ¤rute, sÃ¥ fort man sÃ¤ger att nÃ¥got som hÃ¤nder i nutid Ã¤r historiskt fÃ¥r man hÃ¶ra att man Ã¤r historielÃ¶s. Men jag har Ã¤ndÃ¥ tittat pÃ¥ fotboll i 30â€“35 Ã¥r, och det hÃ¤r mÃ¥let Ã¤r med dÃ¤ruppe. Jag sÃ¤ger inte att det sÃ¤rklassigt Ã¤r det vackraste mÃ¥let som nÃ¥gonsin har gjorts, men det skulle vara med i min diskussion. Om man skulle sÃ¤tta sig och snacka om tio kandidater Ã¤r det hÃ¤r mÃ¥let med.\r\nArsenal vann till slut med 2â€“0, Alex Iwobi gjorde lagets andra mÃ¥l i matchen. Palace skapade nÃ¥gra mÃ¥lchanser i andra halvlek, men mÃ¥lvakten Petr Cech stod i vÃ¤gen. â€Gunnersâ€ hade lÃ¤gen att gÃ¶ra ytterligare mÃ¥l.\r\nArsenal Ã¤r pÃ¥ fjÃ¤rde plats i Premier League efter tre poÃ¤ng mot Crystal Palace.', 1, 7, 3),
(125, '2017-01-01 22:58:24.000000', '0000-00-00 00:00:00.000000', 'Hejja', 'Hejja', 0, 7, 2),
(126, '2017-01-03 01:08:19.000000', '0000-00-00 00:00:00.000000', 'Quantum Aristoxeni', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Equidem, sed audistine modo de Carneade? Ita prorsus, inquam; Duo Reges: constructio interrete. Hoc Hieronymus summum bonum esse dixit. Quonam, inquit, modo? Quid est, quod ab ea absolvi et perfici debeat? Quid me istud rogas? Quid de Platone aut de Democrito loquar?\r\nQuid Zeno?\r\nItaque rursus eadem ratione, qua sum paulo ante usus, haerebitis.\r\nQuibusnam praeteritis?\r\nQuid censes in Latino fore?\r\nMagna laus.\r\nRes enim se praeclare habebat, et quidem in utraque parte.\r\nEasdemne res?\r\nItaque in rebus minime obscuris non multus est apud eos disserendi labor.\r\nNe in odium veniam, si amicum destitero tueri. Ut in geometria, prima si dederis, danda sunt omnia. Quantum Aristoxeni ingenium consumptum videmus in musicis? Sit hoc ultimum bonorum, quod nunc a me defenditur; Haec bene dicuntur, nec ego repugno, sed inter sese ipsa pugnant. Hic Speusippus, hic Xenocrates, hic eius auditor Polemo, cuius illa ipsa sessio fuit, quam videmus. Videamus animi partes, quarum est conspectus illustrior; Prodest, inquit, mihi eo esse animo. Nunc ita separantur, ut disiuncta sint, quo nihil potest esse perversius. Age nunc isti doceant, vel tu potius quis enim ista melius? Beatus sibi videtur esse moriens. At iste non dolendi status non vocatur voluptas. Aliter homines, aliter philosophos loqui putas oportere?\r\nNec enim, omnes avaritias si aeque avaritias esse dixerimus, sequetur ut etiam aequas esse dicamus.\r\nAnimum autem reliquis rebus ita perfecit, ut corpus;\r\nQuamquam ab iis philosophiam et omnes ingenuas disciplinas habemus; Quae est igitur causa istarum angustiarum? Sit sane ista voluptas. Urgent tamen et nihil remittunt. An nisi populari fama? Ab his oratores, ab his imperatores ac rerum publicarum principes extiterunt. \r\n', 1, 3, 2),
(127, '2017-01-03 01:08:29.000000', '0000-00-00 00:00:00.000000', 'En bra affÃ¤r', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Equidem, sed audistine modo de Carneade? Ita prorsus, inquam; Duo Reges: constructio interrete. Hoc Hieronymus summum bonum esse dixit. Quonam, inquit, modo? Quid est, quod ab ea absolvi et perfici debeat? Quid me istud rogas? Quid de Platone aut de Democrito loquar?\r\nQuid Zeno?\r\nItaque rursus eadem ratione, qua sum paulo ante usus, haerebitis.\r\nQuibusnam praeteritis?\r\nQuid censes in Latino fore?\r\nMagna laus.\r\nRes enim se praeclare habebat, et quidem in utraque parte.\r\nEasdemne res?\r\nItaque in rebus minime obscuris non multus est apud eos disserendi labor.\r\nNe in odium veniam, si amicum destitero tueri. Ut in geometria, prima si dederis, danda sunt omnia. Quantum Aristoxeni ingenium consumptum videmus in musicis? Sit hoc ultimum bonorum, quod nunc a me defenditur; Haec bene dicuntur, nec ego repugno, sed inter sese ipsa pugnant. Hic Speusippus, hic Xenocrates, hic eius auditor Polemo, cuius illa ipsa sessio fuit, quam videmus. Videamus animi partes, quarum est conspectus illustrior; Prodest, inquit, mihi eo esse animo. Nunc ita separantur, ut disiuncta sint, quo nihil potest esse perversius. Age nunc isti doceant, vel tu potius quis enim ista melius? Beatus sibi videtur esse moriens. At iste non dolendi status non vocatur voluptas. Aliter homines, aliter philosophos loqui putas oportere?\r\nNec enim, omnes avaritias si aeque avaritias esse dixerimus, sequetur ut etiam aequas esse dicamus.\r\nAnimum autem reliquis rebus ita perfecit, ut corpus;\r\nQuamquam ab iis philosophiam et omnes ingenuas disciplinas habemus; Quae est igitur causa istarum angustiarum? Sit sane ista voluptas. Urgent tamen et nihil remittunt. An nisi populari fama? Ab his oratores, ab his imperatores ac rerum publicarum principes extiterunt. \r\n', 1, 3, 3),
(128, '2017-01-03 01:09:00.000000', '0000-00-00 00:00:00.000000', 'Alla Ã¤r vÃ¤lkommna', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Equidem, sed audistine modo de Carneade? Ita prorsus, inquam; Duo Reges: constructio interrete. Hoc Hieronymus summum bonum esse dixit. Quonam, inquit, modo? Quid est, quod ab ea absolvi et perfici debeat? Quid me istud rogas? Quid de Platone aut de Democrito loquar?\r\nQuid Zeno?\r\nItaque rursus eadem ratione, qua sum paulo ante usus, haerebitis.\r\nQuibusnam praeteritis?\r\nQuid censes in Latino fore?\r\nMagna laus.\r\nRes enim se praeclare habebat, et quidem in utraque parte.\r\nEasdemne res?\r\nItaque in rebus minime obscuris non multus est apud eos disserendi labor.\r\nNe in odium veniam, si amicum destitero tueri. Ut in geometria, prima si dederis, danda sunt omnia. Quantum Aristoxeni ingenium consumptum videmus in musicis? Sit hoc ultimum bonorum, quod nunc a me defenditur; Haec bene dicuntur, nec ego repugno, sed inter sese ipsa pugnant. Hic Speusippus, hic Xenocrates, hic eius auditor Polemo, cuius illa ipsa sessio fuit, quam videmus. Videamus animi partes, quarum est conspectus illustrior; Prodest, inquit, mihi eo esse animo. Nunc ita separantur, ut disiuncta sint, quo nihil potest esse perversius. Age nunc isti doceant, vel tu potius quis enim ista melius? Beatus sibi videtur esse moriens. At iste non dolendi status non vocatur voluptas. Aliter homines, aliter philosophos loqui putas oportere?\r\nNec enim, omnes avaritias si aeque avaritias esse dixerimus, sequetur ut etiam aequas esse dicamus.\r\nAnimum autem reliquis rebus ita perfecit, ut corpus;\r\nQuamquam ab iis philosophiam et omnes ingenuas disciplinas habemus; Quae est igitur causa istarum angustiarum? Sit sane ista voluptas. Urgent tamen et nihil remittunt. An nisi populari fama? Ab his oratores, ab his imperatores ac rerum publicarum principes extiterunt. \r\n', 1, 3, 2),
(129, '2017-01-03 01:09:26.000000', '0000-00-00 00:00:00.000000', 'Natten lider mot sitt slut', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Equidem, sed audistine modo de Carneade? Ita prorsus, inquam; Duo Reges: constructio interrete. Hoc Hieronymus summum bonum esse dixit. Quonam, inquit, modo? Quid est, quod ab ea absolvi et perfici debeat? Quid me istud rogas? Quid de Platone aut de Democrito loquar?\r\nQuid Zeno?\r\nItaque rursus eadem ratione, qua sum paulo ante usus, haerebitis.\r\nQuibusnam praeteritis?\r\nQuid censes in Latino fore?\r\nMagna laus.\r\nRes enim se praeclare habebat, et quidem in utraque parte.\r\nEasdemne res?\r\nItaque in rebus minime obscuris non multus est apud eos disserendi labor.\r\nNe in odium veniam, si amicum destitero tueri. Ut in geometria, prima si dederis, danda sunt omnia. Quantum Aristoxeni ingenium consumptum videmus in musicis? Sit hoc ultimum bonorum, quod nunc a me defenditur; Haec bene dicuntur, nec ego repugno, sed inter sese ipsa pugnant. Hic Speusippus, hic Xenocrates, hic eius auditor Polemo, cuius illa ipsa sessio fuit, quam videmus. Videamus animi partes, quarum est conspectus illustrior; Prodest, inquit, mihi eo esse animo. Nunc ita separantur, ut disiuncta sint, quo nihil potest esse perversius. Age nunc isti doceant, vel tu potius quis enim ista melius? Beatus sibi videtur esse moriens. At iste non dolendi status non vocatur voluptas. Aliter homines, aliter philosophos loqui putas oportere?\r\nNec enim, omnes avaritias si aeque avaritias esse dixerimus, sequetur ut etiam aequas esse dicamus.\r\nAnimum autem reliquis rebus ita perfecit, ut corpus;\r\nQuamquam ab iis philosophiam et omnes ingenuas disciplinas habemus; Quae est igitur causa istarum angustiarum? Sit sane ista voluptas. Urgent tamen et nihil remittunt. An nisi populari fama? Ab his oratores, ab his imperatores ac rerum publicarum principes extiterunt. \r\n', 1, 3, 2),
(130, '2017-01-03 01:09:40.000000', '0000-00-00 00:00:00.000000', 'Det Ã¤r dags att ta bladet ur munnen', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Equidem, sed audistine modo de Carneade? Ita prorsus, inquam; Duo Reges: constructio interrete. Hoc Hieronymus summum bonum esse dixit. Quonam, inquit, modo? Quid est, quod ab ea absolvi et perfici debeat? Quid me istud rogas? Quid de Platone aut de Democrito loquar?\r\nQuid Zeno?\r\nItaque rursus eadem ratione, qua sum paulo ante usus, haerebitis.\r\nQuibusnam praeteritis?\r\nQuid censes in Latino fore?\r\nMagna laus.\r\nRes enim se praeclare habebat, et quidem in utraque parte.\r\nEasdemne res?\r\nItaque in rebus minime obscuris non multus est apud eos disserendi labor.\r\nNe in odium veniam, si amicum destitero tueri. Ut in geometria, prima si dederis, danda sunt omnia. Quantum Aristoxeni ingenium consumptum videmus in musicis? Sit hoc ultimum bonorum, quod nunc a me defenditur; Haec bene dicuntur, nec ego repugno, sed inter sese ipsa pugnant. Hic Speusippus, hic Xenocrates, hic eius auditor Polemo, cuius illa ipsa sessio fuit, quam videmus. Videamus animi partes, quarum est conspectus illustrior; Prodest, inquit, mihi eo esse animo. Nunc ita separantur, ut disiuncta sint, quo nihil potest esse perversius. Age nunc isti doceant, vel tu potius quis enim ista melius? Beatus sibi videtur esse moriens. At iste non dolendi status non vocatur voluptas. Aliter homines, aliter philosophos loqui putas oportere?\r\nNec enim, omnes avaritias si aeque avaritias esse dixerimus, sequetur ut etiam aequas esse dicamus.\r\nAnimum autem reliquis rebus ita perfecit, ut corpus;\r\nQuamquam ab iis philosophiam et omnes ingenuas disciplinas habemus; Quae est igitur causa istarum angustiarum? Sit sane ista voluptas. Urgent tamen et nihil remittunt. An nisi populari fama? Ab his oratores, ab his imperatores ac rerum publicarum principes extiterunt. \r\n', 1, 3, 4),
(131, '2017-01-03 01:10:03.000000', '0000-00-00 00:00:00.000000', 'Varje dag har sin egen musikgenre', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Equidem, sed audistine modo de Carneade? Ita prorsus, inquam; Duo Reges: constructio interrete. Hoc Hieronymus summum bonum esse dixit. Quonam, inquit, modo? Quid est, quod ab ea absolvi et perfici debeat? Quid me istud rogas? Quid de Platone aut de Democrito loquar?\r\nQuid Zeno?\r\nItaque rursus eadem ratione, qua sum paulo ante usus, haerebitis.\r\nQuibusnam praeteritis?\r\nQuid censes in Latino fore?\r\nMagna laus.\r\nRes enim se praeclare habebat, et quidem in utraque parte.\r\nEasdemne res?\r\nItaque in rebus minime obscuris non multus est apud eos disserendi labor.\r\nNe in odium veniam, si amicum destitero tueri. Ut in geometria, prima si dederis, danda sunt omnia. Quantum Aristoxeni ingenium consumptum videmus in musicis? Sit hoc ultimum bonorum, quod nunc a me defenditur; Haec bene dicuntur, nec ego repugno, sed inter sese ipsa pugnant. Hic Speusippus, hic Xenocrates, hic eius auditor Polemo, cuius illa ipsa sessio fuit, quam videmus. Videamus animi partes, quarum est conspectus illustrior; Prodest, inquit, mihi eo esse animo. Nunc ita separantur, ut disiuncta sint, quo nihil potest esse perversius. Age nunc isti doceant, vel tu potius quis enim ista melius? Beatus sibi videtur esse moriens. At iste non dolendi status non vocatur voluptas. Aliter homines, aliter philosophos loqui putas oportere?\r\nNec enim, omnes avaritias si aeque avaritias esse dixerimus, sequetur ut etiam aequas esse dicamus.\r\nAnimum autem reliquis rebus ita perfecit, ut corpus;\r\nQuamquam ab iis philosophiam et omnes ingenuas disciplinas habemus; Quae est igitur causa istarum angustiarum? Sit sane ista voluptas. Urgent tamen et nihil remittunt. An nisi populari fama? Ab his oratores, ab his imperatores ac rerum publicarum principes extiterunt. \r\n', 1, 3, 3),
(132, '2017-01-03 01:10:20.000000', '0000-00-00 00:00:00.000000', 'Torsdagar Ã¤r det Polka som gÃ¤ller', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Equidem, sed audistine modo de Carneade? Ita prorsus, inquam; Duo Reges: constructio interrete. Hoc Hieronymus summum bonum esse dixit. Quonam, inquit, modo? Quid est, quod ab ea absolvi et perfici debeat? Quid me istud rogas? Quid de Platone aut de Democrito loquar?\r\nQuid Zeno?\r\nItaque rursus eadem ratione, qua sum paulo ante usus, haerebitis.\r\nQuibusnam praeteritis?\r\nQuid censes in Latino fore?\r\nMagna laus.\r\nRes enim se praeclare habebat, et quidem in utraque parte.\r\nEasdemne res?\r\nItaque in rebus minime obscuris non multus est apud eos disserendi labor.\r\nNe in odium veniam, si amicum destitero tueri. Ut in geometria, prima si dederis, danda sunt omnia. Quantum Aristoxeni ingenium consumptum videmus in musicis? Sit hoc ultimum bonorum, quod nunc a me defenditur; Haec bene dicuntur, nec ego repugno, sed inter sese ipsa pugnant. Hic Speusippus, hic Xenocrates, hic eius auditor Polemo, cuius illa ipsa sessio fuit, quam videmus. Videamus animi partes, quarum est conspectus illustrior; Prodest, inquit, mihi eo esse animo. Nunc ita separantur, ut disiuncta sint, quo nihil potest esse perversius. Age nunc isti doceant, vel tu potius quis enim ista melius? Beatus sibi videtur esse moriens. At iste non dolendi status non vocatur voluptas. Aliter homines, aliter philosophos loqui putas oportere?\r\nNec enim, omnes avaritias si aeque avaritias esse dixerimus, sequetur ut etiam aequas esse dicamus.\r\nAnimum autem reliquis rebus ita perfecit, ut corpus;\r\nQuamquam ab iis philosophiam et omnes ingenuas disciplinas habemus; Quae est igitur causa istarum angustiarum? Sit sane ista voluptas. Urgent tamen et nihil remittunt. An nisi populari fama? Ab his oratores, ab his imperatores ac rerum publicarum principes extiterunt. \r\n', 1, 3, 4),
(133, '2017-01-03 01:10:42.000000', '0000-00-00 00:00:00.000000', 'NÃ¤r vindarna viskar mitt namn', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Equidem, sed audistine modo de Carneade? Ita prorsus, inquam; Duo Reges: constructio interrete. Hoc Hieronymus summum bonum esse dixit. Quonam, inquit, modo? Quid est, quod ab ea absolvi et perfici debeat? Quid me istud rogas? Quid de Platone aut de Democrito loquar?\r\nQuid Zeno?\r\nItaque rursus eadem ratione, qua sum paulo ante usus, haerebitis.\r\nQuibusnam praeteritis?\r\nQuid censes in Latino fore?\r\nMagna laus.\r\nRes enim se praeclare habebat, et quidem in utraque parte.\r\nEasdemne res?\r\nItaque in rebus minime obscuris non multus est apud eos disserendi labor.\r\nNe in odium veniam, si amicum destitero tueri. Ut in geometria, prima si dederis, danda sunt omnia. Quantum Aristoxeni ingenium consumptum videmus in musicis? Sit hoc ultimum bonorum, quod nunc a me defenditur; Haec bene dicuntur, nec ego repugno, sed inter sese ipsa pugnant. Hic Speusippus, hic Xenocrates, hic eius auditor Polemo, cuius illa ipsa sessio fuit, quam videmus. Videamus animi partes, quarum est conspectus illustrior; Prodest, inquit, mihi eo esse animo. Nunc ita separantur, ut disiuncta sint, quo nihil potest esse perversius. Age nunc isti doceant, vel tu potius quis enim ista melius? Beatus sibi videtur esse moriens. At iste non dolendi status non vocatur voluptas. Aliter homines, aliter philosophos loqui putas oportere?\r\nNec enim, omnes avaritias si aeque avaritias esse dixerimus, sequetur ut etiam aequas esse dicamus.\r\nAnimum autem reliquis rebus ita perfecit, ut corpus;\r\nQuamquam ab iis philosophiam et omnes ingenuas disciplinas habemus; Quae est igitur causa istarum angustiarum? Sit sane ista voluptas. Urgent tamen et nihil remittunt. An nisi populari fama? Ab his oratores, ab his imperatores ac rerum publicarum principes extiterunt. \r\n', 1, 3, 3),
(134, '2017-01-03 01:10:57.000000', '0000-00-00 00:00:00.000000', 'Dagliga ackorÃ¶vningar', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Equidem, sed audistine modo de Carneade? Ita prorsus, inquam; Duo Reges: constructio interrete. Hoc Hieronymus summum bonum esse dixit. Quonam, inquit, modo? Quid est, quod ab ea absolvi et perfici debeat? Quid me istud rogas? Quid de Platone aut de Democrito loquar?\r\nQuid Zeno?\r\nItaque rursus eadem ratione, qua sum paulo ante usus, haerebitis.\r\nQuibusnam praeteritis?\r\nQuid censes in Latino fore?\r\nMagna laus.\r\nRes enim se praeclare habebat, et quidem in utraque parte.\r\nEasdemne res?\r\nItaque in rebus minime obscuris non multus est apud eos disserendi labor.\r\nNe in odium veniam, si amicum destitero tueri. Ut in geometria, prima si dederis, danda sunt omnia. Quantum Aristoxeni ingenium consumptum videmus in musicis? Sit hoc ultimum bonorum, quod nunc a me defenditur; Haec bene dicuntur, nec ego repugno, sed inter sese ipsa pugnant. Hic Speusippus, hic Xenocrates, hic eius auditor Polemo, cuius illa ipsa sessio fuit, quam videmus. Videamus animi partes, quarum est conspectus illustrior; Prodest, inquit, mihi eo esse animo. Nunc ita separantur, ut disiuncta sint, quo nihil potest esse perversius. Age nunc isti doceant, vel tu potius quis enim ista melius? Beatus sibi videtur esse moriens. At iste non dolendi status non vocatur voluptas. Aliter homines, aliter philosophos loqui putas oportere?\r\nNec enim, omnes avaritias si aeque avaritias esse dixerimus, sequetur ut etiam aequas esse dicamus.\r\nAnimum autem reliquis rebus ita perfecit, ut corpus;\r\nQuamquam ab iis philosophiam et omnes ingenuas disciplinas habemus; Quae est igitur causa istarum angustiarum? Sit sane ista voluptas. Urgent tamen et nihil remittunt. An nisi populari fama? Ab his oratores, ab his imperatores ac rerum publicarum principes extiterunt. \r\n', 1, 3, 1),
(135, '2017-01-03 01:11:47.000000', '0000-00-00 00:00:00.000000', 'StÃ¤ndiga fÃ¶rbÃ¤ttringar i studion', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Equidem, sed audistine modo de Carneade? Ita prorsus, inquam; Duo Reges: constructio interrete. Hoc Hieronymus summum bonum esse dixit. Quonam, inquit, modo? Quid est, quod ab ea absolvi et perfici debeat? Quid me istud rogas? Quid de Platone aut de Democrito loquar?\r\nQuid Zeno?\r\nItaque rursus eadem ratione, qua sum paulo ante usus, haerebitis.\r\nQuibusnam praeteritis?\r\nQuid censes in Latino fore?\r\nMagna laus.\r\nRes enim se praeclare habebat, et quidem in utraque parte.\r\nEasdemne res?\r\nItaque in rebus minime obscuris non multus est apud eos disserendi labor.\r\nNe in odium veniam, si amicum destitero tueri. Ut in geometria, prima si dederis, danda sunt omnia. Quantum Aristoxeni ingenium consumptum videmus in musicis? Sit hoc ultimum bonorum, quod nunc a me defenditur; Haec bene dicuntur, nec ego repugno, sed inter sese ipsa pugnant. Hic Speusippus, hic Xenocrates, hic eius auditor Polemo, cuius illa ipsa sessio fuit, quam videmus. Videamus animi partes, quarum est conspectus illustrior; Prodest, inquit, mihi eo esse animo. Nunc ita separantur, ut disiuncta sint, quo nihil potest esse perversius. Age nunc isti doceant, vel tu potius quis enim ista melius? Beatus sibi videtur esse moriens. At iste non dolendi status non vocatur voluptas. Aliter homines, aliter philosophos loqui putas oportere?\r\nNec enim, omnes avaritias si aeque avaritias esse dixerimus, sequetur ut etiam aequas esse dicamus.\r\nAnimum autem reliquis rebus ita perfecit, ut corpus;\r\nQuamquam ab iis philosophiam et omnes ingenuas disciplinas habemus; Quae est igitur causa istarum angustiarum? Sit sane ista voluptas. Urgent tamen et nihil remittunt. An nisi populari fama? Ab his oratores, ab his imperatores ac rerum publicarum principes extiterunt. \r\n', 1, 3, 2),
(136, '2017-01-03 01:12:02.000000', '0000-00-00 00:00:00.000000', 'Musik i vardagen', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Equidem, sed audistine modo de Carneade? Ita prorsus, inquam; Duo Reges: constructio interrete. Hoc Hieronymus summum bonum esse dixit. Quonam, inquit, modo? Quid est, quod ab ea absolvi et perfici debeat? Quid me istud rogas? Quid de Platone aut de Democrito loquar?\r\nQuid Zeno?\r\nItaque rursus eadem ratione, qua sum paulo ante usus, haerebitis.\r\nQuibusnam praeteritis?\r\nQuid censes in Latino fore?\r\nMagna laus.\r\nRes enim se praeclare habebat, et quidem in utraque parte.\r\nEasdemne res?\r\nItaque in rebus minime obscuris non multus est apud eos disserendi labor.\r\nNe in odium veniam, si amicum destitero tueri. Ut in geometria, prima si dederis, danda sunt omnia. Quantum Aristoxeni ingenium consumptum videmus in musicis? Sit hoc ultimum bonorum, quod nunc a me defenditur; Haec bene dicuntur, nec ego repugno, sed inter sese ipsa pugnant. Hic Speusippus, hic Xenocrates, hic eius auditor Polemo, cuius illa ipsa sessio fuit, quam videmus. Videamus animi partes, quarum est conspectus illustrior; Prodest, inquit, mihi eo esse animo. Nunc ita separantur, ut disiuncta sint, quo nihil potest esse perversius. Age nunc isti doceant, vel tu potius quis enim ista melius? Beatus sibi videtur esse moriens. At iste non dolendi status non vocatur voluptas. Aliter homines, aliter philosophos loqui putas oportere?\r\nNec enim, omnes avaritias si aeque avaritias esse dixerimus, sequetur ut etiam aequas esse dicamus.\r\nAnimum autem reliquis rebus ita perfecit, ut corpus;\r\nQuamquam ab iis philosophiam et omnes ingenuas disciplinas habemus; Quae est igitur causa istarum angustiarum? Sit sane ista voluptas. Urgent tamen et nihil remittunt. An nisi populari fama? Ab his oratores, ab his imperatores ac rerum publicarum principes extiterunt. \r\n', 1, 3, 2),
(137, '2017-01-03 01:12:12.000000', '0000-00-00 00:00:00.000000', 'Aldrig bÃ¤ttre Ã¤n nu', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Equidem, sed audistine modo de Carneade? Ita prorsus, inquam; Duo Reges: constructio interrete. Hoc Hieronymus summum bonum esse dixit. Quonam, inquit, modo? Quid est, quod ab ea absolvi et perfici debeat? Quid me istud rogas? Quid de Platone aut de Democrito loquar?\r\nQuid Zeno?\r\nItaque rursus eadem ratione, qua sum paulo ante usus, haerebitis.\r\nQuibusnam praeteritis?\r\nQuid censes in Latino fore?\r\nMagna laus.\r\nRes enim se praeclare habebat, et quidem in utraque parte.\r\nEasdemne res?\r\nItaque in rebus minime obscuris non multus est apud eos disserendi labor.\r\nNe in odium veniam, si amicum destitero tueri. Ut in geometria, prima si dederis, danda sunt omnia. Quantum Aristoxeni ingenium consumptum videmus in musicis? Sit hoc ultimum bonorum, quod nunc a me defenditur; Haec bene dicuntur, nec ego repugno, sed inter sese ipsa pugnant. Hic Speusippus, hic Xenocrates, hic eius auditor Polemo, cuius illa ipsa sessio fuit, quam videmus. Videamus animi partes, quarum est conspectus illustrior; Prodest, inquit, mihi eo esse animo. Nunc ita separantur, ut disiuncta sint, quo nihil potest esse perversius. Age nunc isti doceant, vel tu potius quis enim ista melius? Beatus sibi videtur esse moriens. At iste non dolendi status non vocatur voluptas. Aliter homines, aliter philosophos loqui putas oportere?\r\nNec enim, omnes avaritias si aeque avaritias esse dixerimus, sequetur ut etiam aequas esse dicamus.\r\nAnimum autem reliquis rebus ita perfecit, ut corpus;\r\nQuamquam ab iis philosophiam et omnes ingenuas disciplinas habemus; Quae est igitur causa istarum angustiarum? Sit sane ista voluptas. Urgent tamen et nihil remittunt. An nisi populari fama? Ab his oratores, ab his imperatores ac rerum publicarum principes extiterunt. \r\n', 1, 3, 4);
INSERT INTO `posts` (`post_id`, `create_time`, `edit_time`, `title`, `text`, `is_published`, `user_id`, `cat_id`) VALUES
(138, '2017-01-03 01:12:42.000000', '0000-00-00 00:00:00.000000', 'Vasste garagebanden i STHLM', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Equidem, sed audistine modo de Carneade? Ita prorsus, inquam; Duo Reges: constructio interrete. Hoc Hieronymus summum bonum esse dixit. Quonam, inquit, modo? Quid est, quod ab ea absolvi et perfici debeat? Quid me istud rogas? Quid de Platone aut de Democrito loquar?\r\nQuid Zeno?\r\nItaque rursus eadem ratione, qua sum paulo ante usus, haerebitis.\r\nQuibusnam praeteritis?\r\nQuid censes in Latino fore?\r\nMagna laus.\r\nRes enim se praeclare habebat, et quidem in utraque parte.\r\nEasdemne res?\r\nItaque in rebus minime obscuris non multus est apud eos disserendi labor.\r\nNe in odium veniam, si amicum destitero tueri. Ut in geometria, prima si dederis, danda sunt omnia. Quantum Aristoxeni ingenium consumptum videmus in musicis? Sit hoc ultimum bonorum, quod nunc a me defenditur; Haec bene dicuntur, nec ego repugno, sed inter sese ipsa pugnant. Hic Speusippus, hic Xenocrates, hic eius auditor Polemo, cuius illa ipsa sessio fuit, quam videmus. Videamus animi partes, quarum est conspectus illustrior; Prodest, inquit, mihi eo esse animo. Nunc ita separantur, ut disiuncta sint, quo nihil potest esse perversius. Age nunc isti doceant, vel tu potius quis enim ista melius? Beatus sibi videtur esse moriens. At iste non dolendi status non vocatur voluptas. Aliter homines, aliter philosophos loqui putas oportere?\r\nNec enim, omnes avaritias si aeque avaritias esse dixerimus, sequetur ut etiam aequas esse dicamus.\r\nAnimum autem reliquis rebus ita perfecit, ut corpus;\r\nQuamquam ab iis philosophiam et omnes ingenuas disciplinas habemus; Quae est igitur causa istarum angustiarum? Sit sane ista voluptas. Urgent tamen et nihil remittunt. An nisi populari fama? Ab his oratores, ab his imperatores ac rerum publicarum principes extiterunt. \r\n', 1, 3, 2),
(139, '2017-01-03 01:12:58.000000', '0000-00-00 00:00:00.000000', 'Musikalisk begÃ¥vning', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Equidem, sed audistine modo de Carneade? Ita prorsus, inquam; Duo Reges: constructio interrete. Hoc Hieronymus summum bonum esse dixit. Quonam, inquit, modo? Quid est, quod ab ea absolvi et perfici debeat? Quid me istud rogas? Quid de Platone aut de Democrito loquar?\r\nQuid Zeno?\r\nItaque rursus eadem ratione, qua sum paulo ante usus, haerebitis.\r\nQuibusnam praeteritis?\r\nQuid censes in Latino fore?\r\nMagna laus.\r\nRes enim se praeclare habebat, et quidem in utraque parte.\r\nEasdemne res?\r\nItaque in rebus minime obscuris non multus est apud eos disserendi labor.\r\nNe in odium veniam, si amicum destitero tueri. Ut in geometria, prima si dederis, danda sunt omnia. Quantum Aristoxeni ingenium consumptum videmus in musicis? Sit hoc ultimum bonorum, quod nunc a me defenditur; Haec bene dicuntur, nec ego repugno, sed inter sese ipsa pugnant. Hic Speusippus, hic Xenocrates, hic eius auditor Polemo, cuius illa ipsa sessio fuit, quam videmus. Videamus animi partes, quarum est conspectus illustrior; Prodest, inquit, mihi eo esse animo. Nunc ita separantur, ut disiuncta sint, quo nihil potest esse perversius. Age nunc isti doceant, vel tu potius quis enim ista melius? Beatus sibi videtur esse moriens. At iste non dolendi status non vocatur voluptas. Aliter homines, aliter philosophos loqui putas oportere?\r\nNec enim, omnes avaritias si aeque avaritias esse dixerimus, sequetur ut etiam aequas esse dicamus.\r\nAnimum autem reliquis rebus ita perfecit, ut corpus;\r\nQuamquam ab iis philosophiam et omnes ingenuas disciplinas habemus; Quae est igitur causa istarum angustiarum? Sit sane ista voluptas. Urgent tamen et nihil remittunt. An nisi populari fama? Ab his oratores, ab his imperatores ac rerum publicarum principes extiterunt. \r\n', 1, 3, 1),
(140, '2017-01-03 01:13:11.000000', '0000-00-00 00:00:00.000000', 'Var musikers drÃ¶m', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Equidem, sed audistine modo de Carneade? Ita prorsus, inquam; Duo Reges: constructio interrete. Hoc Hieronymus summum bonum esse dixit. Quonam, inquit, modo? Quid est, quod ab ea absolvi et perfici debeat? Quid me istud rogas? Quid de Platone aut de Democrito loquar?\r\nQuid Zeno?\r\nItaque rursus eadem ratione, qua sum paulo ante usus, haerebitis.\r\nQuibusnam praeteritis?\r\nQuid censes in Latino fore?\r\nMagna laus.\r\nRes enim se praeclare habebat, et quidem in utraque parte.\r\nEasdemne res?\r\nItaque in rebus minime obscuris non multus est apud eos disserendi labor.\r\nNe in odium veniam, si amicum destitero tueri. Ut in geometria, prima si dederis, danda sunt omnia. Quantum Aristoxeni ingenium consumptum videmus in musicis? Sit hoc ultimum bonorum, quod nunc a me defenditur; Haec bene dicuntur, nec ego repugno, sed inter sese ipsa pugnant. Hic Speusippus, hic Xenocrates, hic eius auditor Polemo, cuius illa ipsa sessio fuit, quam videmus. Videamus animi partes, quarum est conspectus illustrior; Prodest, inquit, mihi eo esse animo. Nunc ita separantur, ut disiuncta sint, quo nihil potest esse perversius. Age nunc isti doceant, vel tu potius quis enim ista melius? Beatus sibi videtur esse moriens. At iste non dolendi status non vocatur voluptas. Aliter homines, aliter philosophos loqui putas oportere?\r\nNec enim, omnes avaritias si aeque avaritias esse dixerimus, sequetur ut etiam aequas esse dicamus.\r\nAnimum autem reliquis rebus ita perfecit, ut corpus;\r\nQuamquam ab iis philosophiam et omnes ingenuas disciplinas habemus; Quae est igitur causa istarum angustiarum? Sit sane ista voluptas. Urgent tamen et nihil remittunt. An nisi populari fama? Ab his oratores, ab his imperatores ac rerum publicarum principes extiterunt. \r\n', 1, 3, 4),
(141, '2017-01-03 01:13:29.000000', '0000-00-00 00:00:00.000000', 'Morgonmusik', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Equidem, sed audistine modo de Carneade? Ita prorsus, inquam; Duo Reges: constructio interrete. Hoc Hieronymus summum bonum esse dixit. Quonam, inquit, modo? Quid est, quod ab ea absolvi et perfici debeat? Quid me istud rogas? Quid de Platone aut de Democrito loquar?\r\nQuid Zeno?\r\nItaque rursus eadem ratione, qua sum paulo ante usus, haerebitis.\r\nQuibusnam praeteritis?\r\nQuid censes in Latino fore?\r\nMagna laus.\r\nRes enim se praeclare habebat, et quidem in utraque parte.\r\nEasdemne res?\r\nItaque in rebus minime obscuris non multus est apud eos disserendi labor.\r\nNe in odium veniam, si amicum destitero tueri. Ut in geometria, prima si dederis, danda sunt omnia. Quantum Aristoxeni ingenium consumptum videmus in musicis? Sit hoc ultimum bonorum, quod nunc a me defenditur; Haec bene dicuntur, nec ego repugno, sed inter sese ipsa pugnant. Hic Speusippus, hic Xenocrates, hic eius auditor Polemo, cuius illa ipsa sessio fuit, quam videmus. Videamus animi partes, quarum est conspectus illustrior; Prodest, inquit, mihi eo esse animo. Nunc ita separantur, ut disiuncta sint, quo nihil potest esse perversius. Age nunc isti doceant, vel tu potius quis enim ista melius? Beatus sibi videtur esse moriens. At iste non dolendi status non vocatur voluptas. Aliter homines, aliter philosophos loqui putas oportere?\r\nNec enim, omnes avaritias si aeque avaritias esse dixerimus, sequetur ut etiam aequas esse dicamus.\r\nAnimum autem reliquis rebus ita perfecit, ut corpus;\r\nQuamquam ab iis philosophiam et omnes ingenuas disciplinas habemus; Quae est igitur causa istarum angustiarum? Sit sane ista voluptas. Urgent tamen et nihil remittunt. An nisi populari fama? Ab his oratores, ab his imperatores ac rerum publicarum principes extiterunt. \r\n', 1, 3, 2);

-- --------------------------------------------------------

--
-- Tabellstruktur `users`
--

CREATE TABLE `users` (
  `user_id` int(255) NOT NULL,
  `firstname` varchar(255) COLLATE utf8_swedish_ci NOT NULL,
  `lastname` varchar(255) COLLATE utf8_swedish_ci NOT NULL,
  `email` varchar(255) COLLATE utf8_swedish_ci NOT NULL,
  `password` varchar(255) COLLATE utf8_swedish_ci NOT NULL,
  `profilepic` varchar(255) COLLATE utf8_swedish_ci NOT NULL,
  `role` varchar(255) COLLATE utf8_swedish_ci NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_swedish_ci COMMENT='Användardatabasen';

--
-- Dumpning av Data i tabell `users`
--

INSERT INTO `users` (`user_id`, `firstname`, `lastname`, `email`, `password`, `profilepic`, `role`) VALUES
(3, 'superuser', 'superuser', 'superuser@loop.x', '$2y$10$xBRdo1uZS/5dSSGd1nuZgelONvVWB8hdLy/AYTv02V/AT85wd8NBy', '', 'admin'),
(5, 'Harry', 'Hansson', 'hogsboharry@gbg.se', '$2y$10$Gw8vwMT5Q.RGlaTprU7/8.Vs89o49sAMpoPVgJKpkcPpvf1tzpHD2', '', 'user'),
(6, 'Gunde', 'Svan', 'gsvan@hotmail.com', '$2y$10$uxz04VT6b5FKGIp7P62V9OIuSjR.gwiisWLi/sITFUzgiyERcNKZO', '', 'user'),
(7, 'ko', 'ko', 'ko@ko.com', '$2y$10$3bvVigExg5S7KzE.O.Gp..kFeXePMi8OlnU4c2I3e90U8V8wjhe8q', '', 'user');

--
-- Index för dumpade tabeller
--

--
-- Index för tabell `categories`
--
ALTER TABLE `categories`
  ADD PRIMARY KEY (`cat_id`);

--
-- Index för tabell `comments`
--
ALTER TABLE `comments`
  ADD PRIMARY KEY (`com_id`),
  ADD KEY `fk_post_id` (`fk_post_id`);

--
-- Index för tabell `posts`
--
ALTER TABLE `posts`
  ADD PRIMARY KEY (`post_id`),
  ADD KEY `user_id` (`user_id`),
  ADD KEY `cat_id` (`cat_id`);

--
-- Index för tabell `users`
--
ALTER TABLE `users`
  ADD PRIMARY KEY (`user_id`);

--
-- AUTO_INCREMENT för dumpade tabeller
--

--
-- AUTO_INCREMENT för tabell `categories`
--
ALTER TABLE `categories`
  MODIFY `cat_id` int(255) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=5;
--
-- AUTO_INCREMENT för tabell `comments`
--
ALTER TABLE `comments`
  MODIFY `com_id` int(255) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=18;
--
-- AUTO_INCREMENT för tabell `posts`
--
ALTER TABLE `posts`
  MODIFY `post_id` int(255) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=151;
--
-- AUTO_INCREMENT för tabell `users`
--
ALTER TABLE `users`
  MODIFY `user_id` int(255) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=27;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
